litellm_settings:
  set_verbose: True
  cache: True 
  cache_params:        
    type: redis
    supported_call_types: []
general_settings:
  store_model_in_db: True
  store_prompts_in_spend_logs: True    
    
