litellm_settings:
  cache: true 
  cache_params:        
    type: redis
    namespace: "litellm.caching.caching"
general_settings:
  store_model_in_db: true
  store_prompts_in_spend_logs: true    
    
