litellm_settings:
  success_callback: ["langfuse"]
  set_verbose: True
  cache: True 
  cache_params:        
    type: "redis"
    namespace: "litellm.caching"
    supported_call_types: ["acompletion", "completion", "embedding", "aembedding"]
general_settings:
  store_model_in_db: True
  store_prompts_in_spend_logs: True    
    
